# .goreleaser.yml
before:
  hooks:
    - go mod tidy
builds:
  - id: buildtree
    main: ./cmd/buildtree
    binary: buildtree
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    amd64: x86_64
    arm64: ARM64
  format_overrides:
    - goos: windows
      format: zip