version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: buildtree
    main: ./cmd/buildtree
    binary: buildtree
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ if eq .Os "darwin" }}macOS{{ else }}{{ title .Os }}{{ end }}_
      {{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
release:
  github:
    owner: neomen
    name: buildtree
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'