name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Run tests
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o buildtree-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/buildtree
        env:
          CGO_ENABLED: 0

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildtree-${{ matrix.goos }}-${{ matrix.goarch }}
          path: buildtree-${{ matrix.goos }}-${{ matrix.goarch }}